export const field = [
    { x: 1, y: 1, name: 'a8', piece: { type: 'rook', color: 'black', name: 'blackRook', img: 'blackRook.svg' } },
    { x: 1, y: 2, name: 'b8', piece: { type: 'knight', color: 'black', name: 'blackKnight', img: 'blackKnight.svg' } },
    { x: 1, y: 3, name: 'c8', piece: { type: 'bishop', color: 'black', name: 'blackBishop', img: 'blackBishop.svg' } },
    { x: 1, y: 4, name: 'd8', piece: { type: 'queen', color: 'black', name: 'blackQueen', img: 'blackQueen.svg' } },
    { x: 1, y: 5, name: 'e8', piece: { type: 'king', color: 'black', name: 'blackKing', img: 'blackKing.svg' } },
    { x: 1, y: 6, name: 'f8', piece: { type: 'bishop', color: 'black', name: 'blackBishop', img: 'blackBishop.svg' } },
    { x: 1, y: 7, name: 'g8', piece: { type: 'knight', color: 'black', name: 'blackKnight', img: 'blackKnight.svg' } },
    { x: 1, y: 8, name: 'h8', piece: { type: 'rook', color: 'black', name: 'blackRook', img: 'blackRook.svg' } },

    { x: 2, y: 1, name: 'a7', piece: { type: 'pawn', color: 'black', name: 'blackPawn', img: 'blackPawn.svg' } },
    { x: 2, y: 2, name: 'b7', piece: { type: 'pawn', color: 'black', name: 'blackPawn', img: 'blackPawn.svg' } },
    { x: 2, y: 3, name: 'c7', piece: { type: 'pawn', color: 'black', name: 'blackPawn', img: 'blackPawn.svg' } },
    { x: 2, y: 4, name: 'd7', piece: { type: 'pawn', color: 'black', name: 'blackPawn', img: 'blackPawn.svg' } },
    { x: 2, y: 5, name: 'e7', piece: { type: 'pawn', color: 'black', name: 'blackPawn', img: 'blackPawn.svg' } },
    { x: 2, y: 6, name: 'f7', piece: { type: 'pawn', color: 'black', name: 'blackPawn', img: 'blackPawn.svg' } },
    { x: 2, y: 7, name: 'g7', piece: { type: 'pawn', color: 'black', name: 'blackPawn', img: 'blackPawn.svg' } },
    { x: 2, y: 8, name: 'h7', piece: { type: 'pawn', color: 'black', name: 'blackPawn', img: 'blackPawn.svg' } },

    { x: 3, y: 1, name: 'a6', piece: {} }, { x: 3, y: 2, name: 'b6', piece: {} },
    { x: 3, y: 3, name: 'c6', piece: {} }, { x: 3, y: 4, name: 'd6', piece: {} },
    { x: 3, y: 5, name: 'e6', piece: {} }, { x: 3, y: 6, name: 'f6', piece: {} },
    { x: 3, y: 7, name: 'g6', piece: {} }, { x: 3, y: 8, name: 'h6', piece: {} },

    { x: 4, y: 1, name: 'a5', piece: {} }, { x: 4, y: 2, name: 'b5', piece: {} },
    { x: 4, y: 3, name: 'c5', piece: {} }, { x: 4, y: 4, name: 'd5', piece: {} },
    { x: 4, y: 5, name: 'e5', piece: {} }, { x: 4, y: 6, name: 'f5', piece: {} },
    { x: 4, y: 7, name: 'g5', piece: {} }, { x: 4, y: 8, name: 'h5', piece: {} },

    { x: 5, y: 1, name: 'a4', piece: {} }, { x: 5, y: 2, name: 'b4', piece: {} },
    { x: 5, y: 3, name: 'c4', piece: {} }, { x: 5, y: 4, name: 'd4', piece: {} },
    { x: 5, y: 5, name: 'e4', piece: {} }, { x: 5, y: 6, name: 'f4', piece: {} },
    { x: 5, y: 7, name: 'g4', piece: {} }, { x: 5, y: 8, name: 'h4', piece: {} },

    { x: 6, y: 1, name: 'a3', piece: {} }, { x: 6, y: 2, name: 'b3', piece: {} },
    { x: 6, y: 3, name: 'c3', piece: {} }, { x: 6, y: 4, name: 'd3', piece: {} },
    { x: 6, y: 5, name: 'e3', piece: {} }, { x: 6, y: 6, name: 'f3', piece: {} },
    { x: 6, y: 7, name: 'g3', piece: {} }, { x: 6, y: 8, name: 'h3', piece: {} },

    { x: 7, y: 1, name: 'a2', piece: { type: 'pawn', color: 'white', name: 'whitePawn', img: 'whitePawn.svg' } },
    { x: 7, y: 2, name: 'b2', piece: { type: 'pawn', color: 'white', name: 'whitePawn', img: 'whitePawn.svg' } },
    { x: 7, y: 3, name: 'c2', piece: { type: 'pawn', color: 'white', name: 'whitePawn', img: 'whitePawn.svg' } },
    { x: 7, y: 4, name: 'd2', piece: { type: 'pawn', color: 'white', name: 'whitePawn', img: 'whitePawn.svg' } },
    { x: 7, y: 5, name: 'e2', piece: { type: 'pawn', color: 'white', name: 'whitePawn', img: 'whitePawn.svg' } },
    { x: 7, y: 6, name: 'f2', piece: { type: 'pawn', color: 'white', name: 'whitePawn', img: 'whitePawn.svg' } },
    { x: 7, y: 7, name: 'g2', piece: { type: 'pawn', color: 'white', name: 'whitePawn', img: 'whitePawn.svg' } },
    { x: 7, y: 8, name: 'h2', piece: { type: 'pawn', color: 'white', name: 'whitePawn', img: 'whitePawn.svg' } },

    { x: 8, y: 1, name: 'a1', piece: { type: 'rook', color: 'white', name: 'whiteRook', img: 'whiteRook.svg' } },
    { x: 8, y: 2, name: 'b1', piece: { type: 'knight', color: 'white', name: 'whiteKnight', img: 'whiteKnight.svg' } },
    { x: 8, y: 3, name: 'c1', piece: { type: 'bishop', color: 'white', name: 'whiteBishop', img: 'whiteBishop.svg' } },
    { x: 8, y: 4, name: 'd1', piece: { type: 'queen', color: 'white', name: 'whiteQueen', img: 'whiteQueen.svg' } },
    { x: 8, y: 5, name: 'e1', piece: { type: 'king', color: 'white', name: 'whiteKing', img: 'whiteKing.svg' } },
    { x: 8, y: 6, name: 'f1', piece: { type: 'bishop', color: 'white', name: 'whiteBishop', img: 'whiteBishop.svg' } },
    { x: 8, y: 7, name: 'g1', piece: { type: 'knight', color: 'white', name: 'whiteKnight', img: 'whiteKnight.svg' } },
    { x: 8, y: 8, name: 'h1', piece: { type: 'rook', color: 'white', name: 'whiteRook', img: 'whiteRook.svg' } },
]